// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTasksFromText(arg1) {
  return window['go']['main']['App']['CreateTasksFromText'](arg1);
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}
