// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTasksFromText(arg1:string):Promise<Array<main.Task>>;

export function ListTasks():Promise<Array<main.Task>>;
